site_name: ghops
repo_url: https://github.com/queelius/ghops
repo_name: queelius/ghops
docs_dir: docs
site_dir: site
theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  icon:
    repo: fontawesome/brands/github-alt

nav:
  - Home: index.md
  - Usage: usage.md
  - Changelog: changelog.md
  - Contributing: contributing.md
  - Future Plans: future-plans.md
