name: morning-routine
description: Daily morning repository maintenance routine
version: "1.0"

# Workflow metadata
metadata:
  author: ghops
  schedule: "0 9 * * *"  # Run at 9 AM daily
  timeout: 1800  # 30 minutes max
  notify_on_failure: true

# Global context variables
context:
  max_age: 86400  # 24 hours in seconds
  batch_size: 10
  update_mode: fast-forward

# Task definitions
tasks:
  # Stage 1: Status check
  - id: status-check
    name: Check repository status
    type: ghops
    command: status
    args: ["--all", "--format", "jsonl"]
    output_var: repo_status
    description: Get current status of all repositories

  - id: detect-issues
    name: Detect problematic repositories
    type: python
    depends_on: status-check
    code: |
      import json
      issues = []
      for line in context['repo_status'].split('\n'):
        if line:
          repo = json.loads(line)
          if repo.get('status', {}).get('uncommitted_changes'):
            issues.append({'type': 'uncommitted', 'repo': repo['path']})
          if repo.get('status', {}).get('unpushed_commits'):
            issues.append({'type': 'unpushed', 'repo': repo['path']})
      context['issues'] = issues
      context['has_issues'] = len(issues) > 0

  # Stage 2: Updates
  - id: fetch-updates
    name: Fetch remote updates
    type: parallel
    depends_on: status-check
    tasks:
      - type: shell
        command: "find ${HOME}/repos -name '.git' -type d | xargs -I {} sh -c 'cd {}/.. && git fetch --all --prune'"
        ignore_errors: true

      - type: ghops
        command: update
        args: ["--fetch-only", "--max-age", "${max_age}"]

  - id: check-outdated-deps
    name: Check for outdated dependencies
    type: ghops
    command: query
    args: ["'package.type' == 'python' and last_activity_days > 7"]
    depends_on: fetch-updates
    output_var: outdated_repos
    parse_output: true

  # Stage 3: Clustering analysis
  - id: analyze-clusters
    name: Analyze repository clusters
    type: ghops
    command: cluster analyze
    args: ["--method", "hierarchical", "--show-duplicates"]
    depends_on: [fetch-updates, detect-issues]
    parse_output: true
    output_var: clusters

  - id: report-duplicates
    name: Report duplicate repositories
    type: python
    depends_on: analyze-clusters
    condition: clusters
    code: |
      import json
      duplicates = []
      for cluster in context.get('clusters', []):
        if cluster.get('cluster_type') == 'duplicates':
          duplicates.append(cluster)

      if duplicates:
        print(f"WARNING: Found {len(duplicates)} sets of duplicate repositories")
        for dup in duplicates:
          print(f"  - {', '.join(dup['repositories'])}")

      context['duplicate_count'] = len(duplicates)

  # Stage 4: Maintenance tasks
  - id: cleanup-branches
    name: Clean up merged branches
    type: shell
    depends_on: fetch-updates
    command: |
      for repo in $(ghops list --format json | jq -r '.path'); do
        cd "$repo" && git branch --merged main | grep -v main | xargs -r git branch -d
      done
    ignore_errors: true
    condition: "${CLEANUP_BRANCHES}" == "true"

  - id: update-dependencies
    name: Update Python dependencies
    type: shell
    depends_on: check-outdated-deps
    condition: outdated_repos
    command: |
      echo "${outdated_repos}" | jq -r '.path' | while read repo; do
        if [ -f "$repo/requirements.txt" ]; then
          cd "$repo" && pip-compile --upgrade requirements.in
        fi
      done
    ignore_errors: true

  # Stage 5: Reporting
  - id: generate-summary
    name: Generate morning summary
    type: python
    depends_on: [report-duplicates, cleanup-branches, detect-issues]
    code: |
      import datetime
      summary = {
        'date': datetime.datetime.now().isoformat(),
        'repositories_checked': len(context.get('repo_status', '').split('\n')) - 1,
        'issues_found': len(context.get('issues', [])),
        'duplicates_found': context.get('duplicate_count', 0),
        'status': 'completed'
      }

      print("=== Morning Routine Summary ===")
      print(f"Date: {summary['date']}")
      print(f"Repositories: {summary['repositories_checked']}")
      print(f"Issues: {summary['issues_found']}")
      print(f"Duplicates: {summary['duplicates_found']}")

      context['summary'] = summary

  - id: notify-slack
    name: Send Slack notification
    type: shell
    depends_on: generate-summary
    condition: has_issues
    command: |
      curl -X POST -H 'Content-type: application/json' \
        --data '{"text":"Morning routine found ${issues} issues in repositories"}' \
        ${SLACK_WEBHOOK_URL}
    ignore_errors: true
    on_failure: continue

# Workflow hooks
hooks:
  on_start:
    - type: shell
      command: echo "Starting morning routine at $(date)"

  on_success:
    - type: shell
      command: echo "Morning routine completed successfully"

  on_failure:
    - type: shell
      command: echo "Morning routine failed - check logs"